# pubspec.yaml
# ------------------------------------------------------
# Чистый манифест Wokytoky — без flutter_native_splash
# ------------------------------------------------------

name: wokytoky
description: Matrix client messenger built with Flutter.
publish_to: "none"
version: 0.1.2+2            # versionName 0.1.2, versionCode 2

environment:
  sdk: ">=3.4.0 <4.0.0"

# ── runtime ────────────────────────────────────────────
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.0 

# ── dev-dependencies ──────────────────────────────────
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1   # генерация иконок лаунчера

# ── конфигурация launcher-иконки ──────────────────────
flutter_icons:
  android: true
  ios: false
  image_path: assets/icons/wokyto.png
  min_sdk_android: 21

# ── базовый раздел Flutter ────────────────────────────
flutter:
  uses-material-design: true
  assets:
    - assets/images/woky.png         # runtime-картинка (не splash)
