# pubspec.yaml — конфигурация Flutter-проекта wokytoky
# Обновлено для устранения дублирования ключа `flutter:` и синтаксической ошибки

name: wokytoky
description: Matrix client messenger built with Flutter.
publish_to: "none"
version: 0.1.2+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6               # Иконки для iOS-стиля
  matrix: ^1.0.1                        # Matrix SDK
  sembast: ^3.5.0                       # Хранилище для local storage
  path: ^1.9.0                          # Работа с путями
  path_provider: ^2.1.3                 # Доступ к папкам ОС

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0                 # Стандарты кода
  flutter_launcher_icons: ^0.13.1       # Генерация иконок для приложения

flutter_icons:
  android: true
  ios: false
  image_path: assets/icons/wokyto.png   # Путь до иконки
  min_sdk_android: 21                   # Минимальная версия Android

flutter:
  uses-material-design: true
  assets:
    - assets/images/woky.png            # Логотип или изображение для интерфейса
